[tox]
requires =
    tox>=4
envlist =
    lint
    py{39,310,311,312,313}-django{42,50,51}
skip_missing_interpreters = true

[testenv]
deps =
    django42: Django>=4.2,<5.0
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    djangorestframework>=3.14.0
    djangorestframework-simplejwt>=5.4.0
    pytest
    pytest-django
    requests
commands =
    pytest {posargs}
setenv =
    DJANGO_SETTINGS_MODULE = tests.settings

[testenv:lint]
deps =
    ruff==0.11.0
commands =
    ruff check .
    ruff format --check .
